/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary': '#3a3000',
        'on-tertiary-fixed': '#3f001a',
        'secondary-container': '#ffdb3c',
        'secondary-fixed-dim': '#e9c400',
        'background': '#13140f',
        'primary-fixed-dim': '#92d5a9',
        'surface-container': '#20201b',
        'secondary': '#fff9ef',
        'primary': '#92d5a9',
        'surface-variant': '#35352f',
        'surface-tint': '#92d5a9',
        'surface-dim': '#13140f',
        'on-primary-fixed': '#002110',
        'on-primary': '#00391f',
        'on-error-container': '#ffdad6',
        'tertiary-fixed': '#ffd9e1',
        'on-secondary-fixed': '#221b00',
        'on-surface': '#e5e2da',
        'on-tertiary-container': '#ff8cad',
        'on-background': '#e5e2da',
        'primary-fixed': '#aef2c4',
        'surface-container-low': '#1c1c17',
        'on-error': '#690005',
        'on-tertiary-fixed-variant': '#8f0044',
        'on-secondary-container': '#725f00',
        'error-container': '#93000a',
        'on-surface-variant': '#bfc9bf',
        'tertiary-fixed-dim': '#ffb1c4',
        'surface-bright': '#3a3933',
        'surface-container-high': '#2a2a25',
        'tertiary': '#ffb1c4',
        'on-primary-fixed-variant': '#085230',
        'outline': '#8a938a',
        'surface-container-lowest': '#0e0e0a',
        'on-tertiary': '#65002e',
        'primary-container': '#004d2c',
        'inverse-surface': '#e5e2da',
        'secondary-fixed': '#ffe16d',
        'on-secondary-fixed-variant': '#544600',
        'inverse-primary': '#296a46',
        'surface-container-highest': '#35352f',
        'error': '#ffb4ab',
        'inverse-on-surface': '#31312b',
        'tertiary-container': '#870040',
        'on-primary-container': '#7bbd93',
        'outline-variant': '#404942',
        'surface': '#13140f'
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem'
      },
      spacing: {
        'margin-desktop': '64px',
        xl: '80px',
        md: '24px',
        gutter: '24px',
        base: '8px',
        'margin-mobile': '16px',
        'container-max': '1440px',
        xs: '4px',
        lg: '48px',
        sm: '12px'
      },
      fontFamily: {
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        button: ['Bebas Neue', 'sans-serif'],
        'display-lg-mobile': ['Bebas Neue', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Bebas Neue', 'sans-serif'],
        'headline-xl': ['Bebas Neue', 'sans-serif'],
        'display-lg': ['Bebas Neue', 'sans-serif']
      },
      fontSize: {
        'body-lg': ['20px', { lineHeight: '30px', fontWeight: '400' }],
        button: ['18px', { lineHeight: '18px', letterSpacing: '0.05em', fontWeight: '400' }],
        'display-lg-mobile': ['64px', { lineHeight: '60px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '36px', letterSpacing: '0.05em', fontWeight: '400' }],
        'headline-xl': ['64px', { lineHeight: '64px', letterSpacing: '0.02em', fontWeight: '400' }],
        'display-lg': ['120px', { lineHeight: '110px', letterSpacing: '-0.02em', fontWeight: '400' }]
      }
    }
  },
  plugins: [],
};
